version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./product-categories.db:/fastapi_app/product-categories.db  # Привязываем файл базы данных к контейнеру
    environment:
      - PYTHONUNBUFFERED=1